### ISSUE TITLE
run_inference error

### ISSUE THREAD

**Issue by goalslee** [bendanzzc/AnimateAnyone-reproduction#16]
AnimateAnyone-reproduction$ python run_inference_release.py
layers per block is 2
Loading pipeline components...: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 5/5 [00:00<00:00,  5.83it/s]
  0%|                                                                                                                                                                         | 0/25 [00:01<?, ?it/s]
Traceback (most recent call last):
  File "AnimateAnyone-reproduction/run_inference_release.py", line 236, in <module>
    video_frames = pipeline(ref_image, validation_control_images[:num_frames], decode_chunk_size=2,num_frames=num_frames,motion_bucket_id=127.0, fps=7,controlnet_cond_scale=1.0, width=args['width'], height=args["height"], min_guidance_scale=3.5, max_guidance_scale=3.5, frames_per_batch=frames, num_inference_steps=25, overlap=4).frames[0]
  File ".venv/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "AnimateAnyone-reproduction/pipeline_stable_video_diffusion_controlnet_long.py", line 569, in __call__
    noise_pred = self.unet(
  File ".venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File ".venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File ".venv/lib/python3.10/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
TypeError: UNetSpatioTemporalConditionModel.forward() got an unexpected keyword argument 'down_block_additional_residuals'

could you have a look about this issue?

**Comment by bendanzzc** [comment]
sorry for lots of import error, I have tested and its ok now, please pull the latest version

**Comment by bendanzzc** [comment]
[fix](https://github.com/bendanzzc/AnimateAnyone-reproduction/blob/main/run_inference_release.py#L222)
